# Generated by Django 4.2.7 on 2023-11-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Politicians',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politician_name', models.CharField(max_length=50, verbose_name='politicians name')),
                ('politician_country', models.CharField(max_length=50, verbose_name='politicians country')),
                ('politician_party', models.CharField(max_length=50, verbose_name='politicians party')),
                ('politician_position', models.CharField(max_length=50, verbose_name='politicians position')),
                ('politician_image', models.ImageField(blank=True, null=True, upload_to='politicians')),
            ],
            options={
                'db_table': 'politicians',
            },
        ),
    ]
